# Generated by Django 3.1.5 on 2021-02-24 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formresponse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitteduserinfo',
            name='name_user',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submitteduserinfo',
            name='submitted_user_id',
            field=models.UUIDField(auto_created=True, blank=True, null=True),
        ),
    ]
