# Generated by Django 3.1.7 on 2021-03-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formresponse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submitteduserinfo',
            name='phone_no',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
