# Generated by Django 3.1.5 on 2021-02-27 12:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formresponse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedformresponse',
            name='options_answer_selected',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), size=4),
        ),
    ]
