# Generated by Django 3.1.5 on 2021-02-27 13:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formresponse', '0002_auto_20210227_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedformresponse',
            name='options_answer_selected',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), null=True, size=4),
        ),
    ]
