# Generated by Django 3.1.7 on 2021-03-03 09:28

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formresponse', '0002_auto_20210303_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submittedformresponse',
            name='options_answer_selected',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10), blank=True, null=True, size=4),
        ),
    ]
