# Generated by Django 3.1.5 on 2021-02-26 05:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formresponse', '0002_auto_20210224_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedformresponse',
            name='option_answer_selected',
        ),
        migrations.AddField(
            model_name='submittedformresponse',
            name='options_answer_selected',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submittedformresponse',
            name='answer_given',
            field=models.CharField(max_length=20000, null=True),
        ),
        migrations.AlterField(
            model_name='submitteduserinfo',
            name='submitted_user_id',
            field=models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, null=True),
        ),
    ]
