# Generated by Django 3.1.5 on 2021-03-01 21:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormCreated',
            fields=[
                ('form_name', models.CharField(max_length=100)),
                ('url_key', models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('form_status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionList',
            fields=[
                ('question_id', models.UUIDField(auto_created=True, blank=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=2000)),
                ('question_type', models.CharField(choices=[('text', 'text'), ('radio', 'radio'), ('checkbox', 'checkbox')], default='ANSWER', max_length=100)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formmaker.formcreated')),
            ],
        ),
        migrations.CreateModel(
            name='OptionList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option1', models.CharField(blank=True, max_length=1000, null=True)),
                ('option2', models.CharField(blank=True, max_length=1000, null=True)),
                ('option3', models.CharField(blank=True, max_length=1000, null=True)),
                ('option4', models.CharField(blank=True, max_length=1000, null=True)),
                ('option5', models.CharField(blank=True, max_length=1000, null=True)),
                ('option6', models.CharField(blank=True, max_length=1000, null=True)),
                ('option7', models.CharField(blank=True, max_length=1000, null=True)),
                ('option8', models.CharField(blank=True, max_length=1000, null=True)),
                ('option9', models.CharField(blank=True, max_length=1000, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formmaker.questionlist')),
            ],
        ),
    ]
