# Generated by Django 3.1.5 on 2021-02-20 18:23

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('formmaker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionlist',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='questionlist',
            name='id',
        ),
        migrations.AddField(
            model_name='optionlist',
            name='option10',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='optionlist',
            name='option6',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='optionlist',
            name='option7',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='optionlist',
            name='option8',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='optionlist',
            name='option9',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='question_type',
            field=models.CharField(choices=[('ANSWER', 'ANSWER'), ('RADIO', 'RADIO'), ('CHECKBOX', 'CHECKBOX')], default='ANSWER', max_length=100),
        ),
        migrations.AddField(
            model_name='questionlist',
            name='question_uuid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='optionlist',
            name='option1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='optionlist',
            name='option2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='optionlist',
            name='option3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='optionlist',
            name='option4',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='optionlist',
            name='option5',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
